### ISSUE TITLE
Question: Why an adapter?

### ISSUE THREAD

**Issue by voltechs** [RSully/mac-cec-volume#3]
Is there a reason why an adapter is needed? Is there a reason why one couldn't instruct the OS (macOS) to send said signal/command directly over the HDMI connection?

Pardon my naïveté!

**Comment by RSully** [comment]
macOS does not have any API for sending CEC commands over the built-in HDMI port. If you know of one, or any way to trick it or do it, I'd love to look into it.

**Comment by RSully** [comment]
From https://support.apple.com/en-us/HT204388:

> Do Mac computers with HDMI support CEC (Consumer Electronics Control)?
> 
> Mac computers don't support (and can't control) other devices via CEC connections and HDMI.
